rails destroy scaffold foreign_courses
rails destroy scaffold reviewers
rails destroy scaffold students
rails destroy scaffold tamu_courses
rails destroy scaffold tamu_departments
rails destroy scaffold universities
rails destroy scaffold users
rails destroy scaffold admin
rails destroy scaffold foreign_courses_students
rails destroy scaffold foreign_courses_tamu_courses