 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/foreign_courses_students", type: :request do
  
  # ForeignCoursesStudent. As you add validations to ForeignCoursesStudent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ForeignCoursesStudent.create! valid_attributes
      get foreign_courses_students_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      foreign_courses_student = ForeignCoursesStudent.create! valid_attributes
      get foreign_courses_student_url(foreign_courses_student)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_foreign_courses_student_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      foreign_courses_student = ForeignCoursesStudent.create! valid_attributes
      get edit_foreign_courses_student_url(foreign_courses_student)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ForeignCoursesStudent" do
        expect {
          post foreign_courses_students_url, params: { foreign_courses_student: valid_attributes }
        }.to change(ForeignCoursesStudent, :count).by(1)
      end

      it "redirects to the created foreign_courses_student" do
        post foreign_courses_students_url, params: { foreign_courses_student: valid_attributes }
        expect(response).to redirect_to(foreign_courses_student_url(ForeignCoursesStudent.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ForeignCoursesStudent" do
        expect {
          post foreign_courses_students_url, params: { foreign_courses_student: invalid_attributes }
        }.to change(ForeignCoursesStudent, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post foreign_courses_students_url, params: { foreign_courses_student: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested foreign_courses_student" do
        foreign_courses_student = ForeignCoursesStudent.create! valid_attributes
        patch foreign_courses_student_url(foreign_courses_student), params: { foreign_courses_student: new_attributes }
        foreign_courses_student.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the foreign_courses_student" do
        foreign_courses_student = ForeignCoursesStudent.create! valid_attributes
        patch foreign_courses_student_url(foreign_courses_student), params: { foreign_courses_student: new_attributes }
        foreign_courses_student.reload
        expect(response).to redirect_to(foreign_courses_student_url(foreign_courses_student))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        foreign_courses_student = ForeignCoursesStudent.create! valid_attributes
        patch foreign_courses_student_url(foreign_courses_student), params: { foreign_courses_student: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested foreign_courses_student" do
      foreign_courses_student = ForeignCoursesStudent.create! valid_attributes
      expect {
        delete foreign_courses_student_url(foreign_courses_student)
      }.to change(ForeignCoursesStudent, :count).by(-1)
    end

    it "redirects to the foreign_courses_students list" do
      foreign_courses_student = ForeignCoursesStudent.create! valid_attributes
      delete foreign_courses_student_url(foreign_courses_student)
      expect(response).to redirect_to(foreign_courses_students_url)
    end
  end
end
