 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/reviewers", type: :request do
  
  # Reviewer. As you add validations to Reviewer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Reviewer.create! valid_attributes
      get reviewers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      reviewer = Reviewer.create! valid_attributes
      get reviewer_url(reviewer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_reviewer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      reviewer = Reviewer.create! valid_attributes
      get edit_reviewer_url(reviewer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Reviewer" do
        expect {
          post reviewers_url, params: { reviewer: valid_attributes }
        }.to change(Reviewer, :count).by(1)
      end

      it "redirects to the created reviewer" do
        post reviewers_url, params: { reviewer: valid_attributes }
        expect(response).to redirect_to(reviewer_url(Reviewer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Reviewer" do
        expect {
          post reviewers_url, params: { reviewer: invalid_attributes }
        }.to change(Reviewer, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post reviewers_url, params: { reviewer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested reviewer" do
        reviewer = Reviewer.create! valid_attributes
        patch reviewer_url(reviewer), params: { reviewer: new_attributes }
        reviewer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the reviewer" do
        reviewer = Reviewer.create! valid_attributes
        patch reviewer_url(reviewer), params: { reviewer: new_attributes }
        reviewer.reload
        expect(response).to redirect_to(reviewer_url(reviewer))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        reviewer = Reviewer.create! valid_attributes
        patch reviewer_url(reviewer), params: { reviewer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested reviewer" do
      reviewer = Reviewer.create! valid_attributes
      expect {
        delete reviewer_url(reviewer)
      }.to change(Reviewer, :count).by(-1)
    end

    it "redirects to the reviewers list" do
      reviewer = Reviewer.create! valid_attributes
      delete reviewer_url(reviewer)
      expect(response).to redirect_to(reviewers_url)
    end
  end
end
