 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tamu_departments", type: :request do
  
  # TamuDepartment. As you add validations to TamuDepartment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TamuDepartment.create! valid_attributes
      get tamu_departments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tamu_department = TamuDepartment.create! valid_attributes
      get tamu_department_url(tamu_department)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tamu_department_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tamu_department = TamuDepartment.create! valid_attributes
      get edit_tamu_department_url(tamu_department)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TamuDepartment" do
        expect {
          post tamu_departments_url, params: { tamu_department: valid_attributes }
        }.to change(TamuDepartment, :count).by(1)
      end

      it "redirects to the created tamu_department" do
        post tamu_departments_url, params: { tamu_department: valid_attributes }
        expect(response).to redirect_to(tamu_department_url(TamuDepartment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TamuDepartment" do
        expect {
          post tamu_departments_url, params: { tamu_department: invalid_attributes }
        }.to change(TamuDepartment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tamu_departments_url, params: { tamu_department: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tamu_department" do
        tamu_department = TamuDepartment.create! valid_attributes
        patch tamu_department_url(tamu_department), params: { tamu_department: new_attributes }
        tamu_department.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tamu_department" do
        tamu_department = TamuDepartment.create! valid_attributes
        patch tamu_department_url(tamu_department), params: { tamu_department: new_attributes }
        tamu_department.reload
        expect(response).to redirect_to(tamu_department_url(tamu_department))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tamu_department = TamuDepartment.create! valid_attributes
        patch tamu_department_url(tamu_department), params: { tamu_department: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tamu_department" do
      tamu_department = TamuDepartment.create! valid_attributes
      expect {
        delete tamu_department_url(tamu_department)
      }.to change(TamuDepartment, :count).by(-1)
    end

    it "redirects to the tamu_departments list" do
      tamu_department = TamuDepartment.create! valid_attributes
      delete tamu_department_url(tamu_department)
      expect(response).to redirect_to(tamu_departments_url)
    end
  end
end
