 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/universities", type: :request do
  
  # University. As you add validations to University, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      University.create! valid_attributes
      get universities_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      university = University.create! valid_attributes
      get university_url(university)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_university_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      university = University.create! valid_attributes
      get edit_university_url(university)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new University" do
        expect {
          post universities_url, params: { university: valid_attributes }
        }.to change(University, :count).by(1)
      end

      it "redirects to the created university" do
        post universities_url, params: { university: valid_attributes }
        expect(response).to redirect_to(university_url(University.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new University" do
        expect {
          post universities_url, params: { university: invalid_attributes }
        }.to change(University, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post universities_url, params: { university: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested university" do
        university = University.create! valid_attributes
        patch university_url(university), params: { university: new_attributes }
        university.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the university" do
        university = University.create! valid_attributes
        patch university_url(university), params: { university: new_attributes }
        university.reload
        expect(response).to redirect_to(university_url(university))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        university = University.create! valid_attributes
        patch university_url(university), params: { university: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested university" do
      university = University.create! valid_attributes
      expect {
        delete university_url(university)
      }.to change(University, :count).by(-1)
    end

    it "redirects to the universities list" do
      university = University.create! valid_attributes
      delete university_url(university)
      expect(response).to redirect_to(universities_url)
    end
  end
end
